package org.map.model;

public class MapUserKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_user.id
     *
     * @mbg.generated Fri May 25 21:02:39 CST 2018
     */
    private String id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_user.id
     *
     * @return the value of map_user.id
     *
     * @mbg.generated Fri May 25 21:02:39 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_user.id
     *
     * @param id the value for map_user.id
     *
     * @mbg.generated Fri May 25 21:02:39 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
}